# Assignment 5: 
Team members: 
Jacob Silva
John David
Josh L
[x] Find classification dataset
[]Find the best decision tree for the dataset using 5-fold cross-validation

[]Compute the confidence interval using the bootstrap procedure

In [1]:
import pandas as pd
Data = pd.read_csv('caesarian.csv')
Data

,Age,Delivery number,Delivery time,Blood of Pressure,Heart Problem,Caesarian
0,22,1,0,2,0,False
1,26,2,0,1,0,True
2,26,2,1,1,0,False
3,28,1,0,2,0,False
4,22,2,0,1,0,True
5,26,1,1,0,0,False
6,27,2,0,1,0,False
7,32,3,0,1,0,True
8,28,2,0,1,0,False
9,27,1,1,1,0,True
10,36,1,0,1,0,False
11,33,1,1,0,0,True
12,23,1,1,1,0,False
13,20,1,0,1,1,False
14,29,1,2,0,1,True
15,25,1,2,0,0,False
16,25,1,0,1,0,False
17,20,1,2,2,0,True
18,37,3,0,1,1,True
19,24,1,2,0,1,True
20,26,1,1,1,0,False
21,33,2,0,0,1,True
22,25,1,1,2,0,False
23,27,1,0,0,1,True
24,20,1,0,2,1,True
25,18,1,0,1,0,False
26,18,1,1,2,1,True
27,30,1,0,1,0,False
28,32,1,0,2,1,True
29,26,2,1,1,1,False
...,...,...,...,...,...,...
48,26,2,2,1,0,False
49,29,2,0,0,1,True
50,33,3,2,1,1,False
51,21,2,1,0,1,True
52,30,3,2,2,0,False
53,35,1,1,0,0,False
54,29,2,0,1,1,True
55,25,2,0,1,0,False
56,32,3,1,0,1,True
57,21,1,0,0,0,True
58,26,1,0,2,0,True
59,30,2,1,2,1,True
60,22,1,2,2,0,False
61,19,1,0,1,0,True
62,32,2,0,0,0,True
63,32,2,0,1,1,True
64,31,1,2,2,1,False
65,35,2,0,1,0,True
66,28,3,0,1,0,True
67,29,2,0,1,1,False
68,25,1,0,0,0,True
69,27,2,2,0,0,False
70,17,1,0,0,0,True
71,29,1,2,0,1,True
72,28,2,0,1,0,False
73,32,3,0,1,1,False
74,38,3,2,2,1,True
75,27,2,1,1,0,False
76,33,4,0,1,0,True
77,29,2,1,2,0,True